from __future__ import print_function

import numpy as np
import torch
import torch.nn.functional as F
import torch.optim as optim
from tensorboardX import SummaryWriter

from clients_attackers import *
from server import Server
from utils.adversary import *


def save_cosine_results(server, experiment_name):
    """
    Save all per-round client cosine-similarity matrices generated by
    the `cosine` aggregation rule.

    Saved NPZ fields:
      cosine          -> [T, N, N]
      unique_pairs     -> [T, N*(N-1)/2]
      fedavg_weights   -> [T, N]
      rounds           -> [T]
      pair_i, pair_j   -> client-pair indices
      pairwise_mean
      pairwise_median
      pairwise_std
      pairwise_q25
      pairwise_q75
    """

    agg_weights, cosine_dict = server.return_metrics()

    if len(cosine_dict) == 0:
        raise RuntimeError(
            "No cosine-similarity matrices were recorded. "
            "Use --AR cosine and the modified server.py."
        )

    round_keys = sorted(
        cosine_dict.keys(),
        key=lambda x: int(x)
    )

    cosine_array = np.stack(
        [
            np.asarray(cosine_dict[k], dtype=np.float64)
            for k in round_keys
        ],
        axis=0
    )

    weights_array = np.stack(
        [
            np.asarray(agg_weights[k], dtype=np.float64)
            for k in round_keys
        ],
        axis=0
    )

    if cosine_array.ndim != 3:
        raise ValueError(
            "Expected cosine array with shape [T, N, N], "
            f"got {cosine_array.shape}."
        )

    num_rounds, num_clients, num_clients_2 = cosine_array.shape

    if num_clients != num_clients_2:
        raise ValueError("Cosine matrices must be square.")

    pair_i, pair_j = np.triu_indices(num_clients, k=1)

    unique_pairs = cosine_array[:, pair_i, pair_j]

    pairwise_mean = np.mean(unique_pairs, axis=1)
    pairwise_median = np.median(unique_pairs, axis=1)
    pairwise_std = np.std(unique_pairs, axis=1)
    pairwise_q25 = np.quantile(unique_pairs, 0.25, axis=1)
    pairwise_q75 = np.quantile(unique_pairs, 0.75, axis=1)

    output_path = (
        str(experiment_name)
        + "_cosine_similarity.npz"
    )

    np.savez(
        output_path,
        cosine=cosine_array,
        unique_pairs=unique_pairs,
        fedavg_weights=weights_array,
        rounds=np.asarray(
            [int(k) for k in round_keys],
            dtype=np.int64
        ),
        pair_i=pair_i,
        pair_j=pair_j,
        pairwise_mean=pairwise_mean,
        pairwise_median=pairwise_median,
        pairwise_std=pairwise_std,
        pairwise_q25=pairwise_q25,
        pairwise_q75=pairwise_q75,
    )

    print("\n========================================")
    print("Saved cosine-similarity results")
    print("========================================")
    print("File:", output_path)
    print("Cosine shape:", cosine_array.shape)
    print("Unique-pairs shape:", unique_pairs.shape)
    print("FedAvg weights shape:", weights_array.shape)

    print(
        "Overall mean unique-pair cosine similarity:",
        float(np.mean(unique_pairs))
    )
    print(
        "Overall median unique-pair cosine similarity:",
        float(np.median(unique_pairs))
    )
    print(
        "Overall unique-pair standard deviation:",
        float(np.std(unique_pairs))
    )

    return output_path


def main(args):
    print('#####################')
    print('#####################')
    print('#####################')
    print('#####################')
    print('#####################')
    print('#####################')

    torch.manual_seed(args.seed)

    device = args.device

    writer = SummaryWriter(
        f'./logs/{args.experiment_name}'
    )

    # ----------------------------------------------------------
    # Dataset
    # ----------------------------------------------------------
    if args.dataset == 'mnist':
        from tasks import mnist

        trainData = mnist.train_dataloader(
            args.num_clients,
            loader_type=args.loader_type,
            store=False
        )

        testData = mnist.test_dataloader(
            args.test_batch_size
        )

        Net = mnist.Net
        criterion = F.cross_entropy

    elif args.dataset == 'eurosat':
        from tasks import eurosat

        trainData = eurosat.train_dataloader(
            args.num_clients,
            loader_type=args.loader_type,
            store=False
        )

        testData = eurosat.test_dataloader(
            args.test_batch_size
        )

        Net = eurosat.Net
        criterion = F.cross_entropy

    elif args.dataset == 'resisc':
        from tasks import resisc45

        trainData = resisc45.train_dataloader(
            args.num_clients,
            loader_type=args.loader_type,
            store=True
        )

        testData = resisc45.test_dataloader(
            args.test_batch_size
        )

        Net = resisc45.Net
        criterion = F.cross_entropy

    elif args.dataset == 'cifar':
        from tasks import cifar

        trainData = cifar.train_dataloader(
            args.num_clients,
            loader_type=args.loader_type,
            store=False
        )

        testData = cifar.test_dataloader(
            args.test_batch_size
        )

        Net = cifar.Net
        criterion = F.cross_entropy

    elif args.dataset == 'cifar100':
        from tasks import cifar100

        trainData = cifar100.train_dataloader(
            args.num_clients,
            loader_type=args.loader_type,
            store=False
        )

        testData = cifar100.test_dataloader(
            args.test_batch_size
        )

        Net = cifar100.Net
        criterion = F.cross_entropy

    elif args.dataset == 'fmnist':
        from tasks import fmnist

        trainData = fmnist.train_dataloader(
            args.num_clients,
            loader_type=args.loader_type,
            store=False
        )

        testData = fmnist.test_dataloader(
            args.test_batch_size
        )

        Net = fmnist.Net
        criterion = F.cross_entropy

    else:
        raise ValueError(
            f"Unsupported dataset: {args.dataset}"
        )

    # ----------------------------------------------------------
    # Server
    # ----------------------------------------------------------
    model0 = Net()

    server = Server(
        model0,
        testData,
        criterion,
        device
    )

    server.set_AR(args.AR)

    # ----------------------------------------------------------
    # Clients
    # ----------------------------------------------------------
    model = Net()

    if args.optimizer == 'SGD':
        optimizer = optim.SGD(
            model.parameters(),
            lr=args.lr,
            momentum=args.momentum
        )

    elif args.optimizer == 'Adam':
        optimizer = optim.Adam(
            model.parameters(),
            lr=args.lr
        )

    else:
        raise ValueError(
            f"Unsupported optimizer: {args.optimizer}"
        )

    client_list, labels = adversary_setup(
        args,
        model,
        trainData,
        optimizer,
        criterion,
        device
    )

    server.attach(client_list)
    server.set_clabels(labels)

    # ----------------------------------------------------------
    # Initial evaluation
    # ----------------------------------------------------------
    loss, accuracy, ASR = server.test()

    steps = 0

    writer.add_scalar(
        'test/loss',
        loss,
        steps
    )

    writer.add_scalar(
        'test/accuracy',
        accuracy,
        steps
    )

    if 'BD' in args.type.upper():
        if 'SEMANTIC' in args.attack.upper():
            loss, accuracy, bdata, bpred = (
                server.test_semanticBackdoor()
            )
        else:
            server.backdoor_testing()
            loss, accuracy = (
                server.test_backdoor()
            )

        writer.add_scalar(
            'test/loss_backdoor',
            loss,
            steps
        )

        writer.add_scalar(
            'test/backdoor_success_rate',
            accuracy,
            steps
        )

    elif 'LF' in args.type.upper():
        server.LF_testing()

    # ----------------------------------------------------------
    # Federated training
    # ----------------------------------------------------------
    for j in range(args.epochs):
        steps = j + 1

        print(
            '\n\n########EPOCH %d ########'
            % j
        )

        print(
            '###Model distribution###\n'
        )

        server.distribute()

        group = range(
            args.num_clients
        )

        server.train(group)

        loss, accuracy, ASR = (
            server.test()
        )

        writer.add_scalar(
            'test/loss',
            loss,
            steps
        )

        writer.add_scalar(
            'test/accuracy',
            accuracy,
            steps
        )

        writer.add_scalar(
            'test/ASR',
            ASR,
            steps
        )

        if 'BD' in args.type.upper():
            if 'SEMANTIC' in args.attack.upper():
                loss, accuracy, bdata, bpred = (
                    server.test_semanticBackdoor()
                )
            else:
                loss, accuracy = (
                    server.test_backdoor()
                )

            writer.add_scalar(
                'test/loss_backdoor',
                loss,
                steps
            )

            writer.add_scalar(
                'test/backdoor_success_rate',
                accuracy,
                steps
            )

    writer.close()

    # ----------------------------------------------------------
    # Save gradient statistics
    # ----------------------------------------------------------
    if args.AR.lower() == "stats":
        grad_stats = server.return_grad_stats()

        for key in grad_stats:
            grad_stats[key] = np.array(
                grad_stats[key]
            )

        np.savez(
            str(args.experiment_name)
            + "_gradient_stats.npz",
            **grad_stats
        )

    # ----------------------------------------------------------
    # Save cosine-similarity measurements
    # ----------------------------------------------------------
    if args.AR.lower() == "cosine":
        save_cosine_results(
            server,
            args.experiment_name
        )
